spring:
  application:
    name: speechtotext-api
  profiles:
    active: dev
  
  # Database configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/speechtotext}
    username: ${DATABASE_USER:speechtotext}
    password: ${DATABASE_PASSWORD:speechtotext123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Flyway migration
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

  # Multipart file upload
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  # Jackson JSON configuration
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/css,text/javascript,application/javascript

# Management endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OpenAPI/Swagger documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Application-specific configuration
app:
  # S3/MinIO configuration
  s3:
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    access-key: ${S3_ACCESS_KEY:minioadmin}
    secret-key: ${S3_SECRET_KEY:minioadmin}
    region: ${S3_REGION:us-east-1}
    bucket-name: ${S3_BUCKET:speechtotext-bucket}

  # Upload limits
  upload:
    max-file-size: ${MAX_FILE_SIZE:104857600} # 100MB in bytes

  # Transcription service configuration
  transcription:
    service-url: ${TRANSCRIPTION_SERVICE_URL:http://localhost:8081}
    sync-threshold-seconds: ${SYNC_THRESHOLD:60}
    callback-url: ${CALLBACK_URL:http://api-service:8080/internal/v1/transcriptions}

# Logging configuration
logging:
  level:
    com.speechtotext: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
