# Production profile configuration
spring:
  # Production datasource (use environment variables)
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  # JPA configuration for production
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Production app settings
app:
  s3:
    endpoint: ${S3_ENDPOINT}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET}
    region: ${S3_REGION}

  # Transcription service URL for production
  transcription:
    service-url: ${TRANSCRIPTION_SERVICE_URL}
    callback-url: ${CALLBACK_URL}

# Production logging
logging:
  level:
    com.speechtotext: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: /var/log/api-service/application.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# Production server settings
server:
  compression:
    enabled: true
  http2:
    enabled: true
